name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to the NPM registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: |
            - args: [--frozen-lockfile]

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
